Renamed the command descriptions
terminal42/mage-tools pull request #1
Opened 2017-03-27 12:57 UTC by aschempp

2017-03-27 12:59 UTC, Toflar requested changes

2017-03-27 12:59 UTC, Toflar commented on src/Task/Maintenance/UnlockTask.php
> +        return '[Maintenance] Disabling maintenance mode';
I would name the bundle here.

2017-03-27 12:59 UTC, Toflar commented on src/Task/Symfony/AcceleratorCacheClearTask.php
> +        return '[Symfony] Clear accelerator cache';
I would name the bundle here.

2017-03-27 12:59 UTC, qzminski approved these changes

2017-08-28 08:25 UTC, aschempp commented
ping @terminal42/pilots

2017-08-28 09:28 UTC, aschempp commented
Merged in 18aff560c777d6915f185024187c639b248e9393

2017-08-28 09:28 UTC, closed without merging